server:
  port: 8010

spring:
  thymeleaf:
    cache: false    # 关闭缓存

    # 数据源配置
  datasource:
    url: jdbc:mysql://192.168.30.101:3306/cateyes_data?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456